similar_movies/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user

from similar_movies import db
from .models import User, SavedMovies, WatchedMovies
from similar_movies.email import send_email
from .forms import RegisterForm, LoginForm, ProfileDetailsForm
from flask_bcrypt import Bcrypt


auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    """This view allows user to login"""
    form = LoginForm()
    bcrypt = Bcrypt()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                flash("You are logged in", category="success")
                return redirect(url_for("views.home"))

    return render_template("login.html", form=form, user=current_user)


@auth.route("/signup", methods=["POST", "GET"])
def sign_up():
    """This view allows user to create a new account"""
    form = RegisterForm()
    bcrypt = Bcrypt()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user = User(
            email=form.email.data, username=form.username.data, password=hashed_password
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        send_email(
            "Similar Movies | Sign Up",
            f"Thanks for sign up {new_user.username}",
            new_user.email,
        )
        flash("Welcome on the website", category="success")
        return redirect(url_for("views.home"))
    return render_template("signup.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    """This function allows user to logout"""
    logout_user()
    flash("You have been logged out", category="success")
    return redirect(url_for("views.home"))


@auth.route("/profile")
@login_required
def profile():
    """This view displays user's profile
    user can display and delete saved movies and tv shows"""
    saved_shows = SavedMovies.query.filter_by(user_id=current_user.id).all()
    watched_shows = WatchedMovies.query.filter_by(user_id=current_user.id).all()
    return render_template(
        "profile.html",
        saved_shows=saved_shows,
        watched_shows=watched_shows,
        user=current_user,
    )


@auth.route("/profile/details", methods=["POST", "GET"])
@login_required
def profile_details():
    """This view allows login user to edit additional information"""
    form = ProfileDetailsForm()
    if form.validate_on_submit():
        user_data = User.query.get(current_user.id)

        # This if statements allows to update only 1 element without deleting others
        if form.bio.data:
            user_data.bio = form.bio.data
        if form.country.data:
            user_data.country = form.country.data

        db.session.commit()
        flash("Information saved", category="success")
        return redirect(url_for("auth.profile"))

    return render_template("profile_details.html", form=form, user=current_user)


@auth.route("/admin")
@login_required
def admin():
    """This view display admin dashboard
    admin user is available to delete posts and categories"""
    user_id = current_user.id
    if user_id == 1:
        available_users = User.query.filter_by().all()
        return render_template("admin.html", available_users=available_users)
    else:
        flash("You are not a admin user", category="error")
        return redirect(url_for("views.home"))


@auth.route("/admin/users/<int:user_id>")
@login_required
def user_details(user_id: int):
    """This view allows admin user to check information about every single user"""
    admin_id = current_user.id
    if admin_id == 1:
        user_info = User.query.get(user_id)
        user_saved_shows = SavedMovies.query.filter_by(user_id=user_info.id).all()
        user_watched_shows = WatchedMovies.query.filter_by(user_id=user_info.id).all()
        return render_template(
            "user_details.html",
            user_info=user_info,
            user_saved_shows=user_saved_shows,
            user_watched_shows=user_watched_shows,
        )
    else:
        flash("You are not a admin user", category="error")
        return redirect(url_for("views.home"))


@auth.route("/delete-user/<int:user_id>", methods=["POST"])
@login_required
def delete_user(user_id: int):
    """This function allows to remove movie or tv show from list for login user"""
    user = User.query.get(user_id)
    if user.id != 1:
        db.session.delete(user)
        db.session.commit()
        flash("User deleted", category="success")
        return redirect(url_for("auth.admin"))

    else:
        flash("You can't delete this account!", category="error")
        return redirect(url_for("auth.admin"))


@auth.route("/send-message/<int:user_id>", methods=["POST", "GET"])
@login_required
def send_message(user_id: int):
    """This function allows to send email for user in admin dashboard"""
    if request.method == "POST":
        user = User.query.get(user_id)
        message = request.form.get("message")
        send_email("Static subject", message, user.email)
        flash("Message sent", category="success")
        return redirect(url_for("auth.admin"))

    else:
        return redirect(url_for("auth.admin"))

similar_movies/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required

from similar_movies import db
from similar_movies.models import SavedMovies, WatchedMovies
from similar_movies.search_movie import (
    Similar,
    UpComingMovies,
    PopularMovies,
    SearchVideos,
)

views = Blueprint("views", __name__)


@views.route("/", methods=["POST", "GET"])
def home():
    """This is a main view which display form to search a movie or tv shows"""
    if request.method == "POST":
        title = request.form["title"]
        show_type = request.form["type"]
        return redirect(url_for("views.list_similar_show", title=title, type=show_type))
    else:
        return render_template("home.html")


@views.route("/similar", methods=["GET"])
def list_similar_show():
    """This view allows to display list of similar movies or tv shows"""
    try:
        title = request.args.get("title")
        show_type = request.args.get("type")
        similar_shows = Similar(title, show_type)
        try:
            return_similar_shows = similar_shows.return_similar_shows()
        except IndexError:
            flash("No similar shows for this title", category="error")
        return render_template(
            "list_similar.html",
            return_similar_shows=return_similar_shows,
            title=title,
            show_type=show_type,
        )
    except UnboundLocalError:
        flash("Wrong title, try again", category="error")
        return redirect(url_for("views.home"))


@views.route("/videos/<int:show_id>", methods=["GET"])
def show_videos(show_id):
    """This view allows to display details about movie or tv show"""
    try:
        return_videos = SearchVideos(show_id).return_videos()
        return render_template("show_videos.html", return_videos=return_videos)
    except IndexError:
        flash("Could not display videos for this show", category="error")
        return redirect(url_for("views.home"))


@views.route("/upcoming", methods=["GET"])
def upComing_list():
    """This view is displaying upcoming movies. It has a pagination where 1 page is 1 page from API"""
    page = request.args.get("page", 1, type=int)
    upcoming_movies = UpComingMovies().return_data(page=page)
    return render_template(
        "upcoming_list.html", movies=upcoming_movies, current_page=page
    )


@views.route("/popular/movies", methods=["GET"])
def popular_movies():
    """This view is displaying popular movies.
    It has a pagination where 1 page is 1 page from API"""
    page = request.args.get("page", 1, type=int)
    popular_movie_list = PopularMovies().return_data(page=page)
    return render_template(
        "popular_movies_list.html",
        popular_movie_list=popular_movie_list,
        current_page=page,
    )


@views.route("/save-show", methods=["POST"])
@login_required
def save_show():
    """This function allows to add movie or tv show to list for login user"""
    title = request.form.get("title")
    poster = request.form.get("poster")
    save_shows = SavedMovies(user_id=current_user.id, title=title, image_url=poster)
    db.session.add(save_shows)
    db.session.commit()
    flash("Show saved in your profile", category="success")
    return redirect(url_for("auth.profile"))


@views.route("/delete-show/<int:show_id>", methods=["POST"])
@login_required
def delete_show(show_id):
    """This function allows to remove movie or tv show from list for login user"""
    show = SavedMovies.query.get(show_id)
    if show.user_id != current_user.id:
        flash("You are not allowed to delete this show", category="error")
        return redirect(url_for("auth.profile"))
    db.session.delete(show)
    db.session.commit()
    flash("Show deleted from your profile", category="success")
    return redirect(url_for("auth.profile"))


@views.route("/save-watched", methods=["POST"])
@login_required
def save_watched_show():
    """This function allows to add watched movie or tv show to list for login user"""
    title = request.form.get("title")
    poster = request.form.get("poster")
    save_watched = WatchedMovies(user_id=current_user.id, title=title, image_url=poster)
    db.session.add(save_watched)
    db.session.commit()
    flash("Show saved in your watch history", category="success")
    return redirect(url_for("auth.profile"))


@views.route("/delete-watched/<int:show_id>", methods=["POST"])
@login_required
def delete_watched_show(show_id):
    """This function allows to remove movie or tv show from watched list for login user"""
    show = WatchedMovies.query.get(show_id)
    if show.user_id != current_user.id:
        flash("You are not allowed to delete this show", category="error")
        return redirect(url_for("auth.profile"))
    db.session.delete(show)
    db.session.commit()
    flash("Show deleted from your watch history", category="success")
    return redirect(url_for("auth.profile"))

similar_movies/templates/admin.html
{% extends "base.html" %}


{% block title %}Find similar film{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/admin.css" />
{% endblock %}


{% block content %}

<div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold">Admin dashboard</h1>
</div>


<div class="row justify-content-center text-light">
    <div class="col-auto">
        <div class="table-responsive">
            <div class="table-wrapper-scroll-y my-custom-scrollbar">
            <table class="table-sm border border-secondary table-striped mb-0">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Email</td>
                    <td>Delete User</td>
                    <td>Send message</td>
                </tr>
                </thead>
                <tbody>
                {% for user in available_users %}
                <tr>
                    <td>{{user.id}}</td>
                    <td><a href="admin/users/{{user.id}}">{{user.username}}</td></a>
                    <td>{{user.email}}</td>
                    <td>
                        <form action="{{ url_for('auth.delete_user', user_id=user.id) }}" method="POST">
                            <button class="btn btn-danger" type="submit">Delete user</button>
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        </form>
                    </td>
                    <td>
                        <form action="{{ url_for('auth.send_message', user_id=user.id) }}" method="POST">
                            <input type="text" name="message">
                            <button class="btn btn-success" type="submit">Send message</button>
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

similar_movies/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="static/css/favicon.png">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
  <title>{% block title %}{% endblock %}</title>
  {% block style %}{% endblock %}
  {% block script %}{% endblock %}
</head>
<body>
  {% include "navigation_bar.html" %}

  <!-- ERROR MESSAGES -->
  {% with messages = get_flashed_messages(category_filter=["error"]) %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger  alert-dismissible fade show" role="alert">
          {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
  {% endwith %}

  <!-- END OF ERROR MESSAGES -->


  <!-- SUCCESS MESSAGES -->
  {% with messages = get_flashed_messages(category_filter=["success"]) %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success  alert-dismissible fade show" role="alert">
          {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
  {% endwith %}

  <!-- END OF SUCCESS MESSAGES -->


  <div class="content">
    {% block content %}{% endblock %}

  </div>

<div style="margin-bottom: 100px;"></div>
</body>
{% include "footer.html" %}
</html>

similar_movies/templates/footer.html
<footer class="text-center text-light fixed-bottom bg-dark" style="position: fixed; bottom: 0;">

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Kacper Włodarczyk:
    <a class="text-light" href="https://github.com/DEENUU1/">Github.com</a>
  </div>
</footer>

similar_movies/templates/home.html
{% extends "base.html" %}


{% block title %}Find similar film{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="/static/css/home.css" />
{% endblock %}


{% block content %}

  <div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold">Movie Similar To</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Find similar movies in just a few clicks...</p>
    </div>
  </div>

<div class="container" style="width: 400px;">
<form method="post">
  <div class="input-group mb-3">
    <input autofocus type="text" id="title" name="title" class="form-control" placeholder="Enter a movie or TV show title" aria-label="Recipient's username" aria-describedby="button-addon2" required>
    <button class="btn btn-success" type="submit" id="button-addon2">Search</button>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
  </div>
  <select class="form-select form-select-sm" name="type" id="type">
    <option value="movie">Movie</option>
    <option value="tv">TV Show</option>
  </select>
</form>
</div>


{% endblock %}

similar_movies/templates/list_similar.html
{% extends "base.html" %}

{% block title %} Similar movies to {{movie_name}} {% endblock %}

{% block script %}
    <script src="/static/js/card_animation.js" defer></script>
{% endblock %}


{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/cards.css" />
{% endblock %}

{% block content %}

{% if return_similar_shows %}
<div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold" style="text-transform: uppercase">{{show_type}} similar to "{{title}}"</h1>
</div>



    {% for show in return_similar_shows %}
        <div class="card">
            <img src="https://image.tmdb.org/t/p/w500/{{show.poster}}"/>
            <div class="card-info">

                <h2>{{show.title}}
                <span>({{show.release_date}})</span></h2>
                <p>{{show.overview}}</p>

                <div class="d-flex align-items-center">
                    <form action="{{ url_for('views.save_show') }}" method="POST">
                        <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                        <input type="hidden" name="poster" value="{{show.poster}}">
                        <button type="submit" class="btn btn-success" style="margin-right: 10px;">Watch Later</button>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    </form>

                    <form action="{{ url_for('views.save_watched_show') }}" method="POST">
                        <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                        <input type="hidden" name="poster" value="{{show.poster}}">
                        <button type="submit" class="btn btn-primary mr-2" style="margin-right: 10px;">Already Watched</button>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    </form>

                    <a class="btn btn-primary" href="{{ url_for('views.show_videos', show_id=show.id) }}">VIDEOS</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
<div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold">There is no similar movies/tv shows to {{title}}</h1>
</div>
{% endif %}


{% endblock %}

similar_movies/templates/login.html
{% extends "base.html" %}


{% block title %}Find similar film{% endblock %}

{% block style %}
  <link rel="stylesheet" type="text/css" href="/static/css/login.css" />
{% endblock %}


{% block content %}

<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div class="mb-md-5 mt-md-4 pb-5">
              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your email and password!</p>

              <form method="post">
                {{ form.hidden_tag() }}
                <div class="form-outline form-white mb-4">
                  {{ form.email(class_="form-control form-control-lg", placeholder="Email") }}

                </div>
                <div class="form-outline form-white mb-4">
                  {{ form.password(class_="form-control form-control-lg", placeholder="Password") }}
                </div>
                  {{ form.submit(class_="btn btn-outline-light btn-lg px-5") }}
              </form>
            </div>

            <div>
              <p class="mb-0">Don't have an account? <a href="/signup" class="text-white-50 fw-bold">Sign Up</a></p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

similar_movies/templates/navigation_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MovieSimilarTo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="/upcoming">Upcoming</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/popular/movies">Popular</a>
        </li>
        {% if current_user.id == 1 %}
        <li class="nav-item">
          <a class="nav-link active" href="/admin">Admin</a>
        </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="/profile">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/signup">Sign up</a>
        </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>

similar_movies/templates/popular_movies_list.html
{% extends "base.html" %}

{% block title %} Similar movies to {{movie_name}} {% endblock %}

{% block script %}
    <script src="/static/js/card_animation.js" defer></script>
{% endblock %}


{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/cards.css" />
{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold">Popular movies</h1>
</div>

{% for show in popular_movie_list %}
    <div class="card">
        <img src="https://image.tmdb.org/t/p/w500/{{show.poster}}"/>
        <div class="card-info">
            <h2>{{show.title}}
            <span>({{show.release_date}})</span>
            </h2>
            <p>{{show.overview}}</p>


            <div class="d-flex align-items-center">
                <form action="{{ url_for('views.save_show') }}" method="POST">
                    <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                    <input type="hidden" name="poster" value="{{show.poster}}">
                    <button type="submit" class="btn btn-success" style="margin-right: 10px;">Watch Later</button>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>

                <form action="{{ url_for('views.save_watched_show') }}" method="POST">
                    <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                    <input type="hidden" name="poster" value="{{show.poster}}">
                    <button type="submit" class="btn btn-primary mr-2" style="margin-right: 10px;">Already Watched</button>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>

                <a class="btn btn-primary" href="{{ url_for('views.show_videos', show_id=show.id) }}">VIDEOS</a>

            </div>

        </div>
    </div>
{% endfor %}


<nav style="margin-top: 50px;">
  <ul class="pagination justify-content-center" style="gap: 10px;">
    <li class="page-item"><a class="page-link active" href="?page{{current_page - 1 }}">Previous</a></li>
    <li class="page-item"><a class="page-link active" href="?page={{current_page + 1}}">Next</a></li>
  </ul>
</nav>


{% endblock %}

similar_movies/templates/profile.html
{% extends "base.html" %}


{% block title %}Find similar film{% endblock %}

{% block style %}
<style>
    body {
        background-color: #000000;
     }
</style>
{% endblock %}


{% block content %}


<div class="container">
    <div class="px-4 py-2 my-3 text-center text-dark">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><strong>Welcome, {{user.username}}!</strong></h4>
              {% if user.country %}
              <p class="card-text"><strong>Country</strong>: {{user.country}}</p>
              {% endif %}
              {% if user.bio %}
            <p class="card-text">{{user.bio}}</p>
              {% endif %}
            <a href="profile/details" class="btn btn-primary">Edit your profile</a>
          </div>
        </div>
    </div>
</div>

<div class="px-4 py-2 my-3 text-center text-light">
    <h1 class="display-6 fw-bold">Watch Later</h1>
</div>


{% if saved_shows %}
<div class="row justify-content-center text-light">
    <div class="col-auto">
        <div class="table-responsive">
            <table class="table-sm border border-secondary">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Operation</th>
                    </tr>
                </thead>
                <tbody>
                {% for show in saved_shows %}
                    <tr>
                        <th><img class="rounded float-left" style="width:150px;height:200px;" src="https://image.tmdb.org/t/p/w500/{{show.image_url}}"/></th>
                        <th><h4>{{show.title}}</h4></th>
                        <th>
                            <form action="{{ url_for('views.delete_show', show_id=show.id) }}" method="POST">
                                <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                                <input type="hidden" name="poster" value="{{show.poster}}">
                                <button type="submit" class="btn btn-danger">Delete from Watch Later</button>
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            </form>
                        </th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-center text-light">
    <div class="col-auto">
        <div class="table-responsive">
            <table class="table-sm border border-secondary">
                <thead>
                    <tr>
                        <h1>You don't have any saved movies</h1>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
{% endif %}



<div class="px-4 py-2 my-3 text-center text-light">
    <h1 class="display-6 fw-bold">Watch History</h1>
</div>

{% if watched_shows %}
<div class="row justify-content-center text-light">
    <div class="col-auto">
        <div class="table-responsive">
            <table class="table-sm border border-secondary">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Title</th>
                        <th scope="col">Operation</th>
                    </tr>
                </thead>
                <tbody>
                {% for show in watched_shows %}
                    <tr>
                        <th><img class="rounded float-left" style="width:150px;height:200px;" src="https://image.tmdb.org/t/p/w500/{{show.image_url}}"/></th>
                        <th><h4>{{show.title}}</h4></th>
                        <th>
                            <form action="{{ url_for('views.delete_watched_show', show_id=show.id) }}" method="POST">
                                <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                                <input type="hidden" name="poster" value="{{show.poster}}">
                                <button type="submit" class="btn btn-danger">Delete from Watch Later</button>
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            </form>
                        </th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% else %}
<div class="row justify-content-center text-light">
    <div class="col-auto">
        <div class="table-responsive">
            <table class="table-sm border border-secondary">
                <thead>
                    <tr>
                        <h1>You don't have any saved movies</h1>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

similar_movies/templates/upcoming_list.html
{% extends "base.html" %}

{% block title %} Similar movies to {{movie_name}} {% endblock %}

{% block script %}
    <script src="/static/js/card_animation.js" defer></script>
{% endblock %}


{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/cards.css" />
{% endblock %}

{% block content %}

<div class="px-4 py-5 my-5 text-center text-light">
    <h1 class="display-5 fw-bold">Upcoming movies</h1>
</div>

{% for show in movies %}
    <div class="card">
        <img src="https://image.tmdb.org/t/p/w500/{{show.poster}}"/>
        <div class="card-info">
            <h2>{{show.title}}
            <span>({{show.release_date}})</span>
            </h2>
            <p>{{show.overview}}</p>


            <div class="d-flex align-items-center">
                <form action="{{ url_for('views.save_show') }}" method="POST">
                    <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                    <input type="hidden" name="poster" value="{{show.poster}}">
                    <button type="submit" class="btn btn-success" style="margin-right: 10px;">Watch Later</button>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>

                <form action="{{ url_for('views.save_watched_show') }}" method="POST">
                    <input type="hidden" name="title" value="{{ show.title }} ({{show.release_date}})">
                    <input type="hidden" name="poster" value="{{show.poster}}">
                    <button type="submit" class="btn btn-primary mr-2" style="margin-right: 10px;">Already Watched</button>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                </form>

                <a class="btn btn-primary" href="{{ url_for('views.show_videos', show_id=show.id) }}">VIDEOS</a>

            </div>

        </div>
    </div>
{% endfor %}


<nav style="margin-top: 50px;">
  <ul class="pagination justify-content-center" style="gap: 10px;">
    <li class="page-item"><a class="page-link active" href="?page{{current_page - 1 }}">Previous</a></li>
    <li class="page-item"><a class="page-link active" href="?page={{current_page + 1}}">Next</a></li>
  </ul>
</nav>

{% endblock %}